### ISSUE TITLE
--save-video HTTP Error 403 : Forbidden downloading

### ISSUE THREAD

**Issue by zafai** [bbolli/tumblr-utils#138]
I get this error message when using --save-video

HTTP Error 403: Forbidden downloading

**Comment by Cebtenzzre** [comment]
That's a standard HTTP error code.  It's probably not an issue with tumblr-utils, unless the video in question is actually playable -- such an error generally indicates that the resource is simply not available.  An example URL would be helpful.

**Comment by zafai** [comment]
This is the command I was using. (warning its NSFW)
`./tumblr_backup.py maybe1337 --save-video --save-audio`

**Comment by Cebtenzzre** [comment]
Yeah, that _looks_ to be caused by videos that've been deleted.  If you go to the URLs in a browser you definitely get a 403 error.  There's not much you can do about that, and it's not an issue with tumblr-utils.

Perhaps a developer can comment on whether this might be caused by incorrect URL grabbing, or a lack of proper authentication.  But I doubt it; occasional HTTP errors are normal.

**Comment by zafai** [comment]
You are right!
Thank you for the help just check the media folder and there are some .mp4 files so the other are just down.

**Comment by Hrxn** [comment]
That was caused by the Tumblr video purge a while ago, just for your information.
