### ISSUE TITLE
Incomplete download problem (found 702 posts, download only 111 of them)

### ISSUE THREAD

**Issue by waldens** [bbolli/tumblr-utils#151]
There're 702 posts in my Likes, and tumblr-utils only download 111 posts of them. For others, it just said "HTTP Error 403 : Forbidden downloading"

I searched and #138 said it's not an issue with tumblr-utils, bc these videos are actually unplayable and not accessible. However, I truly can use Chrome to watch these videos normally. so why tumblr-utils cannot backup them?

### Reproduce steps 
(sry it's NSFW, if you are homophobic, I can spend time looking for another example tmr. sry again)
① `py -2 tumblr_backup.py whisperheart --save-video --save-audio -l` to download the content of this page: https://www.tumblr.com/liked/by/whisperheart
② After download finish, open index.html to check the latest content downloaded by tumblr-utils
③ Compared with the latest content on the web page above, a lot less content will be found, for example, [this post](https://imgur.com/Ib862uE) didn't be downloaded successfully.

**Comment by Cebtenzzre** [comment]
@waldens Your "example post" gives a 404.

**Comment by waldens** [comment]
@Cebtenzzre sry, removed by screenshot hosting site bc nsfw, updated the [imgur link](https://imgur.com/Ib862uE) just now.

The screenshot mainly takes the first post on [liked page](https://www.tumblr.com/liked/by/whisperheart) as an example. In fact, through a little comparison we can tell, the 1st 2nd 6th 7th 8th 9th 10th posts on this page from top to bottom are all not successfully downloaded, and they're accessible on browser.

**Comment by waldens** [comment]
Maybe nothing to do with this issue, but another weird discovery:
https://www.tumblr.com/liked/by/bootislands

I liked 4 posts with another tumblr account just for testing purpose:
https://www.tumblr.com/liked/by/bootislands
we can clearly see the liked page says "4 things bootislands likes", but there're only 2 posts in this page. weird. but still different from the case above, in which we can see the post in browser.

**Comment by Cebtenzzre** [comment]
I was able to reproduce the issue with standard tumblr-utils, however with the changes proposed by #114 (tested using a git clone of [this](https://github.com/aggroskater/tumblr-utils)) I was able to successfully download 319 posts.  I'm still not sure why it's less than the expected 700+.

I compared the results to an equivalent download done by TumblThree, and I found that the performance of tumblr-utils was far better -- not only did TumblThree find ~100 _less_ likes, but it also just downloaded a dump of images and videos instead of a proper index.  As far as I know, TumblThree scrapes the `/liked/by` page directly.
