### ISSUE TITLE
Error downloading from SoundCloud

### ISSUE THREAD

**Issue by KimikoMuffin** [bbolli/tumblr-utils#153]
When downloading audio on Windows, it sometimes throws an error like this, which seems to be particularly coming from SoundCloud posts:

`[Errno 22] invalid mode ('wb') or filename: u'D:\\Output\\media\\stream?client_id=N2eHz8D7GtXSl6fTtcGHdSJiS74xqOUI.mp3' downloading http://api.soundcloud.com/tracks/142436023/stream?client_id=N2eHz8D7GtXSl6fTtcGHdSJiS74xqOUI`

The problem seems to be that it is misinterpreting `stream?client_id=` as part of the filename, and Windows does not support question marks in path names.

**Comment by Cebtenzzre** [comment]
I checked, and surprisingly enough that _is_ a valid mp3 file.
In general, we should not be including the query string in the output filenames.  In this particular case we should probably use youtube-dl, if available, because it includes the actual title in the filename and is able to download the file without the client ID.  Otherwise the filename should come from the track ID.
