### ISSUE TITLE
Do embedded movies get downloaded?

### ISSUE THREAD

**Issue by humanitiesclinic** [bbolli/tumblr-utils#171]
I have some posts where Instagram and youtube movies are embedded in the original, but they are not downloaded. Is it possible with the current version of the script to do so? If yes, what command line option should I use?

**Comment by Cebtenzzre** [comment]
Use `--save-video`.  You'll need the `youtube_dl` package for Python 2.
You can install it by running `python -m pip install youtube_dl` in a command prompt.
For future reference, you can run most console programs with `--help` (the Unix-y way) or `/?` (the DOS-y way) in order to see the flags they will accept.
